### ISSUE TITLE
delta load

### ISSUE THREAD

**Issue by rakesh-silswal** [Qlik-PE/qlik-azure-cost-explorer#3]
in azure billing API, value keeps changing (some internal recon). So any consumer has to keep reloading data for same date multiple times.

in my python based solution i do T-20 window shift (so each day has atleast 20 chance). Then i simply do truncate load for any overlap days at my end.

how are you handling this scenario?

also, Azure API is paging based, and i have noticed that Azure return different error code e.g. 429 (too many hits), etc for which wait and retry is only option. how are you taking care of it? do we have access to that part?

if we are interested in amortized cost and expanded at meter details. I know my URL looks like following. how to achieve this in your app?

`https://management.azure.com/subscriptions/XXXXXXXXXX/providers/Microsoft.Billing/billingPeriods/202207/providers/Microsoft.Consumption/usageDetails?api-version=2021-10-01&$expand=meterDetails&metric=amortizedcost`

**Comment by cleveranjos** [comment]
>> in my python based solution i do T-20 window shift (so each day has atleast 20 chance). Then i simply do truncate load for any overlap days at my end.
The user can configure the variable MONTHS (numeric) indicating how many months should be reloaded (usually 2 would be enough)
>> Azure API is paging based, and i have noticed that Azure return different error code e.g. 429 (too many hits), etc for which wait and retry is only option. how are you taking care of it? do we have access to that part?
I faced this situation, currently I´m retrying 10x increasing a sleep time
        tries=tries+1; 
        exit sub when tries > 10;
        trace ******* Incrementing tries to $(tries) ******;
        Sleep 1000*tries;

>> if we are interested in amortized cost and expanded at meter details. I know my URL looks like following. how to achieve this in your app?
if you look at row 39 at modules section there is the URL template, if the fields returned by your your endpoint is the same, I assume that only that row should be changed

**Comment by rakesh-silswal** [comment]
my bad. I assumed your API "CostManagement" and that is why i asked about T-20, because with CostManagement you can go to daily level.

as you are using Billing, month is the lowest cycle we can go to. So you are write 2 month should be good enough.

but running this app daily is a overkill, but necessary (if user requires latest dashboard). how long does your code run? for me each run for one sub takes appox 1 hr (on a good day). and i have 4 sub. And i cannot run it in parallel too, as i will keep getting 429 error code.

can you see you working with CostManagement API? where you can make it run on smaller subset and hence reducing run time?

**Comment by cleveranjos** [comment]
I´m collecting one month each time for the sake of simplicity, but it is possible going daily.
Currently, I calculate startdate and enddate to correspond to month start/end
https://management.azure.com/subscriptions/$(subscriptionId)/providers/Microsoft.Consumption/usageDetails?api-version=2021-10-01&$top=$(bulk)&startDate='&**Date(MonthStart(Today(),-months),'YYYY-MM-DD')**&'&endDate='&**Date(MonthEnd(Today(),-months),'YYYY-MM-DD')**;

**Comment by rakesh-silswal** [comment]
thanks.

it is certainly a good initiative. I have 2 questions, where does your code stores JSON? because json size is significant for billing api (for me its 1.6 gb) per month per subscription. my 3 year worth of data is approx 75GB
On qlik-cloud how does storage billing works.

also is qlik cloud is right place to run this type of compute? for eg. running for loop of GPUs, can be run. but should we?

sorry 1 more.

how does schema evaluation work in Qlik? as source is json, does click traverse thru files and when it sees change, it changes and rerun files? how many such runs are allowed? how forgiving it is to initial schema change? 

i have tried reading billing file via 2 of the best tools (Dremio, and Databricks) in market and still i struggled. when schema evolved, i was on mercy of code on how many such drifts are allowed. if tool could not read extra tag in last json, then i did not see it in my final dataset. (so only way was to keep rerunning it and hoping i would see those rare tags in source json in my final data set). Atleast with spark, i can give schema where i now give most expansive schema). how does Qlik handle this?

**Comment by cleveranjos** [comment]
Thanks for your interesting questions:
1) where does your code store JSON?
I don´t store the JSON itself. The script parses the endpoint answer, gets the content and stores the monthly result as a qvd file. If you´re not familiar with this format, think of it as "csv on steroids". As an example, a typical month of my testing data has 259,991rows/79cols and requires 82.36MB to be stored as a file
2) qlik cloud is right place to run this type of compute? for eg. running for loop of GPUs, can be run. but should we?
This use case is way behind Qlik Cloud capabilities. The final application holding data since Jan/2022 holds 2,769,742 rows of data and requires 130Mb (compressed). Qlik Cloud can (by default) support apps up to 5Gb (additional capacity is available via add-ons. I´m still refining the app, dropping useless fields (from my perspective)
3) how does schema evaluation work in Qlik? as source is json, does click traverse thru files and when it sees change, it changes and rerun files? If something changes, I would need to run the wizard that parses the json response and evaluate the differences. It is not automatic, but it would be easier for small changes (field renaming, new fields, etc)
4) how many such runs are allowed? no limits
5) On qlik-cloud how does storage billing works. Qlik does not charge for storage

**Comment by cleveranjos** [comment]
You can try Qlik Cloud using this link https://www.qlik.com/us/trial/qlik-sense-business-b
This trial has some limits:
1) 30 days
2) Apps up to 2.5Gb (I guess could store easily 25 millions of rows)

**Comment by rakesh-silswal** [comment]
you are awesome, and thanks for taking time to answer my queries.

we are already on Qlik cloud. 

we already have 3 year worth of billing data in ADLS in form of deltalake exposed via databricks. Code for ingestion is written in python (azure function) and final data is in form of deltalake.

now we are trying to bring this data in Qlik cloud using databricks connector (via partner connect). but facing issue. Opened a sperate ticket for it. 

but then we stumbled upon your article in linkedin and though can end-to-end thing run on Qlik. mentally we are not there yet. but good to know options.

**Comment by cleveranjos** [comment]
Good to hear that you´re already on Qlik Cloud. You will love it.
Since you already have the data, you can easily create a data connection using this: https://help.qlik.com/en-US/cloud-services/Subsystems/ODBC_Connector_help/Content/Connectors_ODBC/Databricks/Create-Databricks-connection.htm

Using that connection, instead of retrieving the files (as this app does), you can use SQL to retrieve only the columns and rows you might be interested in, making your life much, much easier. You would use only my charts and read directly from Databricks

Just info, after some columns drop, my app now is consuming 73Mb, way behind Qlik Cloud capabilities (5Gb)

![Captura de tela 2022-08-24 092912](https://user-images.githubusercontent.com/9040310/186419808-6a101c5a-dd24-4dea-972e-e1588be72aea.png)
